service:
  dm_api_account: "http://5.63.153.31:5051"
  mailhog: "http://5.63.153.31:5025"

user:
  login: "kirka"
  password: "qwerty123"

telegram:
  chat_id: -1003480570289
  token: 8393401811:AAGXeKv6UGDlrageDTDBfxCKvtdXmpMGJkQ